baseURL = "https://leveler.xyz"
theme   = "drybones"
title   = "Example site"

[Params]
mainSections = "post"
subtitle     = "An example site for hugo theme development"

[markup.tableOfContents]
endLevel   = 6
ordered    = false
startLevel = 1
