description = "minimal boilerplate theme with tachyons"
features    = []
homepage    = "https://github.com/brendantang/hugo-drybones"
license     = "MIT"
licenselink = "https://github.com/brendantang/hugo-drybones/blob/master/LICENSE"
min_version = "0.65.0"
name        = "basic-tachyons"
tags        = ["blog", "simple"]

[author]
homepage = "https://brendantang.net/"
name     = "brendantang"
